#!/usr/bin/env sh

# Gradle Wrapper script for Unix-based systems
# This script is generated by Gradle. Do not modify it manually.

# Define the location of the Gradle Wrapper properties file
WRAPPER_PROPERTIES_FILE="gradle/wrapper/gradle-wrapper.properties"

# Define the location of the Gradle Wrapper jar file
WRAPPER_JAR_FILE="gradle/wrapper/gradle-wrapper.jar"

# Define the location of the Gradle distribution URL
WRAPPER_URL="https://services.gradle.org/distributions/gradle-8.2-bin.zip"

# Define the location of the Gradle home directory
GRADLE_HOME=".gradle"

# Define the location of the Gradle user home directory
GRADLE_USER_HOME="$HOME/.gradle"

# Define the location of the Gradle distribution directory
GRADLE_DIST_DIR="$GRADLE_HOME/wrapper/dists"

# Define the location of the Gradle wrapper directory
WRAPPER_DIR="gradle/wrapper"

# Define the location of the Gradle wrapper properties file
WRAPPER_PROPERTIES_FILE="$WRAPPER_DIR/gradle-wrapper.properties"

# Define the location of the Gradle wrapper jar file
WRAPPER_JAR_FILE="$WRAPPER_DIR/gradle-wrapper.jar"

# Define the location of the Gradle distribution URL
WRAPPER_URL="https://services.gradle.org/distributions/gradle-8.2-bin.zip"

# Define the location of the Gradle home directory
GRADLE_HOME=".gradle"

# Define the location of the Gradle user home directory
GRADLE_USER_HOME="$HOME/.gradle"

# Define the location of the Gradle distribution directory
GRADLE_DIST_DIR="$GRADLE_HOME/wrapper/dists"

# Define the location of the Gradle wrapper directory
WRAPPER_DIR="gradle/wrapper"

# Define the location of the Gradle wrapper properties file
WRAPPER_PROPERTIES_FILE="$WRAPPER_DIR/gradle-wrapper.properties"

# Define the location of the Gradle wrapper jar file
WRAPPER_JAR_FILE="$WRAPPER_DIR/gradle-wrapper.jar"

# Define the location of the Gradle distribution URL
WRAPPER_URL="https://services.gradle.org/distributions/gradle-8.2-bin.zip"

# Define the location of the Gradle home directory
GRADLE_HOME=".gradle"

# Define the location of the Gradle user home directory
GRADLE_USER_HOME="$HOME/.gradle"

# Define the location of the Gradle distribution directory
GRADLE_DIST_DIR="$GRADLE_HOME/wrapper/dists"

# Define the location of the Gradle wrapper directory
WRAPPER_DIR="gradle/wrapper"

# Define the location of the Gradle wrapper properties file
WRAPPER_PROPERTIES_FILE="$WRAPPER_DIR/gradle-wrapper.properties"

#
