name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Check build logs
      run: cat build/reports/tests/test/index.html

    - name: List build directory
      run: ls -la build/libs

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ATPlugin
        path: build/libs/*.jar
