name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'adopt'
    - name: Download Gradle Wrapper
      run: |
        curl -L https://github.com/gradle/gradle/raw/master/gradlew -o gradlew
        curl -L https://github.com/gradle/gradle/raw/master/gradlew.bat -o gradlew.bat
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Run build with Gradle Wrapper
      run: ./gradlew build
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: AtPlugin
        path: build/libs/at-plugin-1.0-SNAPSHOT.jar
