name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Initialize Gradle Wrapper
      run: |
        ./gradlew wrapper --gradle-version=8.2 --distribution-type=all
    - name: Build with Gradle
      run: ./gradlew build
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ATPlugin
        path: build/libs/*.jar
