name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'adopt'

    - name: Download and set up Gradle Wrapper
      run: |
        mkdir -p gradle/wrapper
        curl -L https://services.gradle.org/distributions/gradle-8.4-bin.zip -o gradle.zip
        unzip -q gradle.zip -d gradle
        mv gradle/gradle-8.4/bin/gradle gradlew
        chmod +x gradlew
        echo "distributionBase=GRADLE_USER_HOME" > gradle/wrapper/gradle-wrapper.properties
        echo "distributionPath=wrapper/dists" >> gradle/wrapper/gradle-wrapper.properties
        echo "distributionUrl=https://services.gradle.org/distributions/gradle-8.4-bin.zip" >> gradle/wrapper/gradle-wrapper.properties
        echo "zipStoreBase=GRADLE_USER_HOME" >> gradle/wrapper/gradle-wrapper.properties
        echo "zipStorePath=wrapper/dists" >> gradle/wrapper/gradle-wrapper.properties
        rm -rf gradle gradle.zip

    - name: Run build with Gradle Wrapper
      run: ./gradlew build

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: AtPlugin
        path: build/libs/at-plugin-1.0-SNAPSHOT.jar
